### ISSUE TITLE
Request for Code Release

### ISSUE THREAD

**Issue by yifeng-cheng** [mickeykang16/TemporalEventStereo#1]
Dear Authors,

I hope you're doing well. I just read your paper and found it very interesting. I'm keen to dive deeper into the work and was wondering when the code will be released.

Could you please let me know the expected timeline for the code release? I believe having access to it would be incredibly beneficial for my research.

Thank you for your time and assistance.

**Comment by mickeykang16** [comment]
Hello @yifeng-cheng,

We appreciate your interest in our work. 

We are currently preparing for a code release with better readability.

The expected timeline is 2 weeks from this point.
